$downloadsFolder = [System.IO.Path]::Combine($env:USERPROFILE, "Downloads")
$internalRepo = "C:\Users\eaguilarher2\Documents\Antigravity\kof-sap-dashboard\pdf_history"

Write-Host "Buscando la Minuta PDF mas reciente en $downloadsFolder..." -ForegroundColor Cyan

# Find the most recent PDF generated by the dashboard
$latestPdf = Get-ChildItem -Path $downloadsFolder -Filter "KOF_Minuta_*.pdf" | Sort-Object LastWriteTime -Descending | Select-Object -First 1

if ($latestPdf) {
    Write-Host "Se encontro: $($latestPdf.Name)" -ForegroundColor Green
    
    $destination = [System.IO.Path]::Combine($internalRepo, $latestPdf.Name)
    
    # Copy the file to the internal repository
    Copy-Item -Path $latestPdf.FullName -Destination $destination -Force
    
    Write-Host "EXITO: Copia guardada correctamente en el repositorio interno: $internalRepo" -ForegroundColor Green
    Write-Host "La copia original sigue existiendo en tus Descargas." -ForegroundColor DarkGray
}
else {
    Write-Host "ERROR: No se encontro ningun archivo KOF_Minuta_*.pdf en tus Descargas." -ForegroundColor Red
    Write-Host "Asegurate de haber dado clic a 'Exportar a Minuta' en el Dashboard primero." -ForegroundColor DarkGray
}

Write-Host "`nPresiona cualquier tecla para salir..."
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
